services:
  baker:
    build:
      context: .
      dockerfile: docker/latest.Dockerfile
    env_file:
      - .env
    user: '1000:1000'
    tty: false
#    volumes:
#      - ./riq/data-fe:/app:z
#      - .data/ui/node_modules:/app/node_modules:z
#      - .data/ui/.next:/app/.next:z
#      - ./docker/ui.sh:/app/run.sh:z
#    command: sh run.sh