services:
  baker:
    build:
      context: .
      dockerfile: docker/latest.Dockerfile
    env_file:
      - .env
    tty: false
    volumes:
      - .:/app:z
      - ./docker/.bashrc:/root/.bashrc
#    command: sh run.sh
