services:
  baker:
    build:
      context: .
      dockerfile: docker/latest.Dockerfile
    env_file:
      - .env
    user: '1000:1000'
    tty: false
    volumes:
      - .:/app:z
      - ./docker/run.sh:/app/run.sh:z
    command: sh run.sh
