services:
  baker:
    build:
      context: .
      dockerfile: docker/latest.Dockerfile
    env_file:
      - .env
    tty: false
    volumes:
      - .:/app:z
      - ./docker/.bashrc:/root/.bashrc
    working_dir: /app
    #entrypoint: 'bash run.sh'
    command: "/bin/sh -c 'trap exit TERM; while :; do sleep 1h & wait $${!}; done;'"

